# -*- coding: utf-8 -*-
#
# Ansible playbook to handle package installs
#
---
- name: Setup environment
  hosts: localhost
  gather_facts: true
  vars:
    packages:
      Fedora:
        - ansible
        - banner
        - bash-completion
        - cowsay
        - curl
        - dos2unix
        - figlet
        - findutils
        - git
        - iotop
        - jq
        - lsof
        - man-db
        - man-pages
        - nmap
        - nmap-ncat
        - npm
        - psmisc
        - rsync
        - shellcheck
        - terraform
        - tig
        - tmux
        - tree
        - vagrant
        - wget
        - xpanes

      Ubuntu:
        - ansible
        - bash-completion
        - cargo
        - cowsay
        - curl
        - dos2unix
        - figlet
        - findutils
        - git
        - golang-go
        - iotop
        - jq
        - lsof
        - man-db
        - ncat
        - nmap
        - npm
        - plocate
        - psmisc
        - python3-pip
        - rsync
        - ruby
        - ruby-dev
        - ruby-rubygems
        - shellcheck
        - sysvbanner
        - terraform
        - tig
        - tmux
        - tmux-xpanes
        - tree
        - vagrant
        - wget

  tasks:
    - name: Install favorite OS packages
      become: true
      package:
        state: present
        name: "{{ packages[ansible_distribution] }}"

    - name: Install python3 pips
      ansible.builtin.pip:
        state: present
        executable: /usr/bin/pip3
        extra_args: "--user"
        name:
          - awscli
          - cf2tf
          - cfn-flip
          - checkov
          - json2yaml
          - pipdeptree
          - pre-commit
          - yamllint

    - name: Install Ruby gems
      community.general.gem:
        state: present
        user_install: true
        name: "{{item}}"
      loop: # gem module name: only supports strings, not a list ☹️
        - bundler
        - mdl
        - pry
        - rake
        - rubocop

    - name: Install node.js npms
      become: true
      npm:
        state: present
        name: "{{item}}"
      loop:
        - prettier

    - name: Install go gos
      shell:
        state: present
        name: "{{item}}"
      loop:
        - mvdan.cc/sh/v3/cmd/shfmt@latest

    - name: Install Rust cargos
      community.general.cargo:
        state: present
        name:
          - diffr
