# -*- coding: utf-8 -*-
---
- name: Setup environment
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install favorite OS packages
      become: true
      package:
        state: present
        name:
          - ShellCheck
          - ansible
          - banner
          - bash-completion
          - cowsay
          - curl
          - figlet
          - findutils
          - git
          - jq
          - lsof
          - man-db
          - man-pages
          - nmap
          - nmap-ncat
          - npm
          - psmisc
          - rsync
          - tig
          - tree
          - vagrant
          - vim-enhanced
          - wget
          - xpanes

    - name: Install python3 pips
      ansible.builtin.pip:
        state: present
        executable: /usr/bin/pip3
        name: "{{item}}"
      loop:
        - awscli
        - cfn-flip
        - checkov
        - json2yaml

    - name: Install Ruby gems
      gem:
        state: present
        user_install: true
        name: "{{item}}"
      loop:
        - bundler
        - mdl
        - pry
        - rake

    - name: Install node.js npms
      become: true
      npm:
        state: present
        global: true
        name: "{{item}}"
      loop:
        - alex
        - write-good
        - prettier

      # - name: Download and compile tmux
      #   block:
