# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mounted='mount | column -t'

# Gitconfigs
alias s='git status'
alias b='git branch -av'
alias d='git diff'
alias r='git remote -v'

# misc
set -o vi
export PS1='[\u@\h]\$ '
